name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên máy ảo Linux Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Lấy code về

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Cài đặt Node.js version 20

      - name: Install dependencies
        run: npm install  # Cài đặt thư viện

      - name: Lint
        run: npm run lint  # Kiểm tra lỗi cú pháp (Lint)

      - name: Run unit tests
        run: npm test  # Chạy test tự động